import from ...lib.utils { cn }
import from "@hugeicons/react" { HugeiconsIcon }
import from "@hugeicons/core-free-icons" { Loading03Icon }

def:pub Spinner(props: any) -> JsxElement {
    return
        <HugeiconsIcon
            icon={Loading03Icon}
            strokeWidth={2}
            role="status"
            aria-label="Loading"
            {**props}
            className={cn("size-4 animate-spin", props["className"])}
        />;
}
